import type { MenuRubricRule } from './menuRubricClassification';

// The backbone mirrors broad food group systems (USDA/FAO/Codex style).
// Keep this generic: new cuisines should map into these categories without
// adding dish-specific keys.
export const menuBaseFoodCategoryRubric: readonly MenuRubricRule[] = [
  {
    key: 'lean_meat_poultry',
    label: 'Lean meat/poultry',
    points: -3,
    prompt: 'Dominant item is lean poultry or lean red meat, usually grilled, roasted, baked, or sliced.',
    reason: 'Lean meat or poultry is usually lighter than fried, creamy, or rich-meat options.',
    terms: ['chicken breast', 'grilled chicken', 'turkey', 'lean beef', 'sirloin', 'pork tenderloin', 'kebab', 'satay'],
    contributorEvidence: 'protective',
  },
  {
    key: 'fatty_or_rich_meat',
    label: 'Fatty/rich meat',
    points: 8,
    prompt: 'Dominant item is richer meat such as burger patty, ribs, pork belly, lamb, duck, brisket, or fatty steak.',
    reason: 'Richer meats add fat load, which can slow digestion and matter for reflux-sensitive profiles.',
    terms: ['burger', 'smash patty', 'beef patty', 'ribeye', 'short rib', 'ribs', 'pork belly', 'duck', 'lamb', 'brisket', 'gyro meat', 'carnitas'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['GERD / reflux', 'GERD / Acid reflux'], multiplier: 1.25 },
      { conditions: ['Sensitive stomach', 'Gastroparesis'], multiplier: 1.12 },
    ],
    sensitivityLabels: ['high-fat foods', 'fatty meat'],
  },
  {
    key: 'processed_meat',
    label: 'Processed meat',
    points: 13,
    prompt: 'Dominant item is cured, smoked, salted, or processed meat such as bacon, sausage, pepperoni, hot dog, ham, salami, chorizo, spam, or deli meat.',
    reason: 'Processed meats often stack fat, salt, spices, and preservatives.',
    terms: ['bacon', 'sausage', 'pepperoni', 'salami', 'hot dog', 'corn dog', 'ham', 'chorizo', 'spam', 'prosciutto', 'deli meat', 'pastrami'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['GERD / reflux', 'GERD / Acid reflux'], multiplier: 1.18 },
      { conditions: ['Sensitive stomach', 'Histamine sensitivity'], multiplier: 1.12 },
    ],
    sensitivityLabels: ['processed meat', 'high-fat foods'],
  },
  {
    key: 'lean_seafood',
    label: 'Lean seafood',
    points: -5,
    prompt: 'Dominant item is lean fish or shellfish such as cod, tuna, white fish, shrimp, crab, scallop, squid, octopus, clam, or oyster.',
    reason: 'Lean seafood tends to be lighter unless sauce, raw prep, or frying changes the risk.',
    terms: ['cod', 'tuna', 'maguro', 'white fish', 'halibut', 'snapper', 'shrimp', 'ebi', 'crab', 'scallop', 'hotate', 'squid', 'ika', 'yakiika', 'yai kika', 'octopus', 'tako', 'clam', 'oyster'],
    contributorEvidence: 'protective',
  },
  {
    key: 'fatty_seafood',
    label: 'Fatty seafood',
    points: 2,
    prompt: 'Dominant item is naturally richer fish such as salmon, yellowtail, mackerel, eel, sardine, trout, black cod, or fish collar.',
    reason: 'Fatty seafood is often nutritious, but its richness can matter for reflux or slow-digestion profiles.',
    terms: ['salmon', 'shake', 'yellowtail', 'hamachi', 'mackerel', 'saba', 'eel', 'unagi', 'sardine', 'trout', 'black cod', 'salmon collar', 'fish collar', 'kama'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['GERD / reflux', 'GERD / Acid reflux', 'Gastroparesis'], multiplier: 1.25 },
    ],
    sensitivityLabels: ['high-fat foods'],
  },
  {
    key: 'egg_based',
    label: 'Egg-based',
    points: 3,
    prompt: 'Dominant item is egg, omelet, frittata, tamago, quiche, egg salad, custard, or egg-forward breakfast food.',
    reason: 'Egg is not a universal trigger, but it adds a small protein/fat signal.',
    terms: ['egg', 'eggs', 'omelet', 'omelette', 'frittata', 'tamago', 'quiche', 'egg salad', 'custard'],
    contributorEvidence: 'ingredient',
  },
  {
    key: 'dairy_based',
    label: 'Dairy-based',
    points: 9,
    prompt: 'Dominant item is milk, cheese, yogurt, ice cream, cream sauce, queso, paneer, ricotta, or cheese-forward dish.',
    reason: 'Dairy-based foods can matter for lactose, fat load, and reflux patterns.',
    terms: ['cheese', 'milk', 'cream', 'yogurt', 'ice cream', 'queso', 'paneer', 'ricotta', 'mozzarella', 'mac and cheese', 'cheese curd'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['Lactose intolerance'], multiplier: 1.75 },
      { conditions: ['GERD / reflux', 'GERD / Acid reflux'], multiplier: 1.18 },
      { conditions: ['IBS'], multiplier: 1.1 },
    ],
    exceptionTerms: ['lactose-free', 'lactose free', 'dairy-free', 'dairy free'],
    sensitivityLabels: ['dairy', 'lactose', 'milk', 'cheese'],
  },
  {
    key: 'wheat_grain_based',
    label: 'Wheat/gluten grain base',
    points: 6,
    prompt: 'Dominant base is wheat/gluten grain such as bread, bun, pasta, ramen, udon, couscous, tortilla, pizza crust, pastry, dumpling, or batter.',
    reason: 'Wheat and gluten-containing bases matter more for gluten-sensitive and some IBS profiles.',
    terms: ['bread', 'bun', 'pasta', 'spaghetti', 'macaroni', 'lasagna', 'penne', 'fettuccine', 'linguine', 'ramen', 'udon', 'couscous', 'tortilla', 'pizza', 'flatbread', 'pastry', 'dumpling', 'wonton', 'noodle', 'flour', 'batter'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['Celiac', 'Celiac disease'], multiplier: 3.4 },
      { conditions: ['Gluten sensitivity'], multiplier: 3 },
      { conditions: ['IBS', 'High FODMAP sensitivity'], multiplier: 1.12 },
    ],
    sensitivityLabels: ['gluten', 'wheat'],
  },
  {
    key: 'non_wheat_grain_based',
    label: 'Non-wheat grain base',
    points: -2,
    prompt: 'Dominant base is rice, oats, corn, quinoa, millet, buckwheat, teff, or another non-wheat grain.',
    reason: 'Non-wheat grains, especially rice, are often gentler starch bases.',
    terms: ['rice', 'sushi rice', 'oats', 'oatmeal', 'corn', 'polenta', 'quinoa', 'millet', 'buckwheat', 'teff', 'arepa'],
    contributorEvidence: 'protective',
  },
  {
    key: 'root_tuber_starch_based',
    label: 'Root/tuber starch base',
    points: 1,
    prompt: 'Dominant base is potato, sweet potato, cassava, taro, yam, plantain, yucca, or similar starchy root/tuber.',
    reason: 'Root and tuber starches are usually moderate, but prep style drives the final score.',
    terms: ['potato', 'fries', 'sweet potato', 'cassava', 'yucca', 'taro', 'yam', 'plantain', 'hash brown', 'gnocchi'],
    contributorEvidence: 'ingredient',
  },
  {
    key: 'legume_soy_pulse_based',
    label: 'Legume/soy/pulse base',
    points: 8,
    prompt: 'Dominant item is beans, lentils, chickpeas, peas, hummus, edamame, tofu, tempeh, soybeans, dal, or falafel.',
    reason: 'Legumes and soy can be fermentable enough to matter for bloating-prone profiles.',
    terms: ['bean', 'beans', 'lentil', 'lentils', 'chickpea', 'hummus', 'pea', 'edamame', 'soy bean', 'soybean', 'tofu', 'tempeh', 'dal', 'falafel'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['IBS', 'High FODMAP sensitivity', 'SIBO'], multiplier: 1.3 },
    ],
    exceptionTerms: ['peanut', 'peanuts', 'peanut butter', 'peanut flour', 'peanut oil', 'soy protein isolate', 'soy sauce', 'soy lecithin', 'tofu', 'tempeh'],
    sensitivityLabels: ['beans', 'soy', 'legumes'],
  },
  {
    key: 'low_fermentation_vegetable_based',
    label: 'Lower-fermentation vegetables',
    points: -2,
    prompt: 'Dominant item is typically gentler vegetables such as lettuce, cucumber, carrot, zucchini, tomato-free salad greens, bell pepper, bok choy, spinach, or seaweed.',
    reason: 'These vegetables usually drive less fermentable load than alliums or crucifers.',
    terms: ['lettuce', 'cucumber', 'carrot', 'zucchini', 'bell pepper', 'bok choy', 'spinach', 'seaweed', 'nori', 'green bean'],
    contributorEvidence: 'protective',
  },
  {
    key: 'high_fermentation_vegetable_based',
    label: 'Higher-fermentation vegetables',
    points: 6,
    prompt: 'Dominant item is cruciferous, allium-heavy, mushroom-heavy, or otherwise gassy vegetables such as onion, garlic, broccoli, cauliflower, cabbage, brussels sprouts, asparagus, artichoke, or mushrooms.',
    reason: 'These vegetables can be healthy but gassier for IBS, bloating, and FODMAP-sensitive profiles.',
    terms: ['onion', 'garlic', 'broccoli', 'cauliflower', 'cabbage', 'brussels sprout', 'brussels sprouts', 'asparagus', 'artichoke', 'mushroom', 'coleslaw'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['IBS', 'High FODMAP sensitivity', 'SIBO'], multiplier: 1.25 },
    ],
  },
  {
    key: 'fruit_based',
    label: 'Fruit-based',
    points: 2,
    prompt: 'Dominant item is fruit, smoothie, juice, fruit dessert, dried fruit, or fruit topping.',
    reason: 'Fruit risk depends on fructose/polyol load, acidity, portion, and smoothie/juice concentration.',
    terms: ['fruit', 'apple', 'pear', 'mango', 'watermelon', 'peach', 'cherry', 'banana', 'berries', 'strawberry', 'orange', 'lemon', 'lime', 'smoothie', 'juice', 'dried fruit'],
    contributorEvidence: 'ingredient',
  },
  {
    key: 'nuts_seeds_or_oils_based',
    label: 'Nuts/seeds/oils',
    points: 2,
    prompt: 'Dominant item is nuts, seeds, nut butter, tahini, pesto, avocado, olives, or oil-forward food.',
    reason: 'Nuts, seeds, and oils can be fine, but fat load and portion can change tolerance.',
    terms: ['almond', 'walnut', 'cashew', 'pistachio', 'peanut', 'seed', 'sesame', 'tahini', 'nut butter', 'pesto', 'avocado', 'olive', 'oil'],
    contributorEvidence: 'ingredient',
  },
  {
    key: 'dessert_sweet_based',
    label: 'Dessert/sweet',
    points: 10,
    prompt: 'Dominant item is dessert, candy, cake, pastry, cookie, brownie, donut, milkshake, sweet drink, syrup-heavy item, or sweet breakfast.',
    reason: 'Desserts can stack sugar, fat, dairy, wheat, chocolate, or large portions.',
    terms: ['dessert', 'cake', 'cookie', 'brownie', 'donut', 'doughnut', 'candy', 'chocolate', 'ice cream', 'milkshake', 'syrup', 'waffle', 'pancake'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['IBS', 'GERD / reflux', 'GERD / Acid reflux', 'Sensitive stomach'], multiplier: 1.08 },
    ],
  },
  {
    key: 'non_alcoholic_beverage',
    label: 'Non-alcoholic beverage',
    points: 2,
    prompt: 'Dominant item is a drink without alcohol, including water, juice, soda, coffee, tea, smoothie, shake, kombucha, or energy drink.',
    reason: 'Beverage risk is mostly driven by carbonation, caffeine, acid, sugar, dairy, or polyols.',
    terms: ['drink', 'beverage', 'water', 'juice', 'soda', 'coffee', 'tea', 'matcha', 'smoothie', 'shake', 'kombucha', 'energy drink'],
    contributorEvidence: 'description',
  },
  {
    key: 'alcoholic_beverage',
    label: 'Alcoholic beverage',
    points: 16,
    prompt: 'Dominant item is beer, wine, sake, cocktail, liquor, hard seltzer, cider, or another alcoholic drink.',
    reason: 'Alcohol is a common reflux and gut-irritation trigger.',
    terms: ['beer', 'wine', 'sake', 'cocktail', 'margarita', 'liquor', 'vodka', 'whiskey', 'whisky', 'tequila', 'rum', 'gin', 'cider', 'hard seltzer'],
    contributorEvidence: 'ingredient',
    conditionMultipliers: [
      { conditions: ['GERD / reflux', 'GERD / Acid reflux'], multiplier: 1.5 },
      { conditions: ['IBS', 'Sensitive stomach'], multiplier: 1.15 },
    ],
    sensitivityLabels: ['alcohol'],
  },
  {
    key: 'sauce_condiment_or_dressing',
    label: 'Sauce/condiment/dressing',
    points: 8,
    prompt: 'Dominant item is a sauce, condiment, dressing, dip, salsa, chutney, glaze, marinade, spread, or add-on.',
    reason: 'Sauces and condiments often hide garlic, onion, acid, spice, dairy, sugar, or fat.',
    terms: ['sauce', 'dressing', 'dip', 'salsa', 'chutney', 'glaze', 'marinade', 'spread', 'aioli', 'mayo', 'ranch', 'ketchup', 'mustard'],
    contributorEvidence: 'uncertainty',
  },
  {
    key: 'soup_stew_or_broth',
    label: 'Soup/stew/broth',
    points: 2,
    prompt: 'Dominant item is soup, stew, curry, chili, ramen broth, pho, consomme, bisque, or broth bowl.',
    reason: 'Soups range from gentle broth to creamy, spicy, bean-heavy, or onion-heavy.',
    terms: ['soup', 'stew', 'broth', 'pho', 'ramen', 'curry', 'chili', 'bisque', 'consomme', 'gumbo'],
    contributorEvidence: 'description',
  },
  {
    key: 'mixed_dish_or_entree',
    label: 'Mixed dish/entree',
    points: 5,
    prompt: 'Use when the item is a mixed dish whose dominant base is not one clear group: bowl, entree, combo, sandwich, burger, pizza, taco, burrito, roll, plate, platter, casserole, or loaded appetizer.',
    reason: 'Mixed dishes need modifier-based scoring because several ingredients and prep methods can stack.',
    terms: ['bowl', 'entree', 'combo', 'sandwich', 'burger', 'pizza', 'taco', 'burrito', 'roll', 'plate', 'platter', 'casserole', 'loaded', 'appetizer'],
    contributorEvidence: 'rubric',
  },
  {
    key: 'unknown',
    label: 'Unknown food base',
    points: 8,
    prompt: 'Use only when the menu item is too ambiguous to classify into any other base category.',
    reason: 'Unclear food detail keeps some uncertainty in the score.',
    terms: [],
    contributorEvidence: 'uncertainty',
  },
];
